version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gestion-db
    ports:
      - "3307:3306"  # Changé pour éviter conflit
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestiondb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gestion-network

  backend:
    image: fatymbengue/gestion-commande-backend:latest
    container_name: gestion-backend
    ports:
      - "8085:8085"  # Gardé (libre)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestiondb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - gestion-network

  frontend:
    image: fatymbengue/gestion-commande-frontend:latest
    container_name: gestion-frontend
    ports:
      - "80:80"  # Gardé (libre)
    depends_on:
      - backend
    networks:
      - gestion-network

volumes:
  db_data:

networks:
  gestion-network:
    driver: bridge